/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/model/untitled2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/untitled2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} scale={0.336} />
    </group>
  )
}

useGLTF.preload('/untitled2.glb')
